name = "PseudoPotentialIO"
uuid = "cb339c56-07fa-4cb2-923a-142469552264"
authors = ["Austin Zadoks", "Bruno Ploumhans", "Michael F. Herbst"]
version = "0.3.0"

[deps]
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
EzXML = "8f5d6c58-4d21-5cfd-889c-e3ad7ee6a615"
PeriodicTable = "7b2266bf-644c-5ea3-82d8-af4bbd25a884"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"

[compat]
DocStringExtensions = "0.9"
EzXML = "1"
PeriodicTable = "1"
Printf = "1"
Statistics = "1"
JuliaFormatter = "2"
julia = "1.6"

[extras]
JuliaFormatter = "98e50ef6-434e-11e9-1051-2b60c6c9e899"

[targets]
precommit = ["JuliaFormatter"]
