name = "PseudoPotentialIO"
uuid = "cb339c56-07fa-4cb2-923a-142469552264"
authors = ["Austin Zadoks"]
version = "0.2.0"

[deps]
Artifacts = "56f22d72-fd6d-98f1-02f0-08ddc0907c33"
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
EzXML = "8f5d6c58-4d21-5cfd-889c-e3ad7ee6a615"
LazyArtifacts = "4af54fe1-eca0-43a8-85a7-787d91b784e3"
Libxc = "66e17ffc-8502-11e9-23b5-c9248d0eb96d"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
PeriodicTable = "7b2266bf-644c-5ea3-82d8-af4bbd25a884"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
SHA = "ea8e919c-243c-51af-8825-aaa63cd721ce"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"

[compat]
Artifacts = "1"
DocStringExtensions = "0.9"
EzXML = "1"
LazyArtifacts = "1"
LinearAlgebra = "1"
Libxc = "0.3"
PeriodicTable = "1"
Printf = "1"
SHA = "0.7"
Statistics = "1"
Test = "1"
JuliaFormatter = "2"
julia = "1.6"

[extras]
JuliaFormatter = "98e50ef6-434e-11e9-1051-2b60c6c9e899"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
precommit = ["JuliaFormatter"]
test = ["Test"]
